<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Report Card</title>
    <style>
        body {
            font-family: "DejaVu Sans", sans-serif;
            color: #1f2937;
            margin: 0;
            padding: 24px;
            background: #ffffff;
        }

        .header {
            margin-bottom: 24px;
        }

        .header h1 {
            font-size: 22px;
            margin: 0 0 8px;
        }

        .header p {
            margin: 2px 0;
            font-size: 12px;
            color: #4b5563;
        }

        .student-info {
            display: flex;
            flex-wrap: wrap;
            gap: 12px;
            margin-bottom: 24px;
        }

        .info-box {
            flex: 1 1 180px;
            border: 1px solid #d1d5db;
            padding: 12px;
            border-radius: 8px;
            background: #f9fafb;
        }

        .info-box strong {
            display: block;
            font-size: 10px;
            color: #6b7280;
            margin-bottom: 6px;
            text-transform: uppercase;
            letter-spacing: 0.08em;
        }

        .info-box span {
            display: block;
            font-size: 14px;
            color: #111827;
            font-weight: 600;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 24px;
        }

        th,
        td {
            padding: 10px 12px;
            border: 1px solid #e5e7eb;
            text-align: left;
            font-size: 12px;
        }

        th {
            background: #f3f4f6;
            font-weight: 700;
            color: #111827;
        }

        .text-center {
            text-align: center;
        }

        .summary {
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 16px;
            padding: 16px;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            background: #f9fafb;
        }

        .summary div {
            font-size: 12px;
        }

        .summary .value {
            font-size: 20px;
            font-weight: 700;
            color: #111827;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Student Grade Report Card</h1>
        <p>Generated by the grading system</p>
    </div>

    <div class="student-info">
        <div class="info-box">
            <strong>Student Name</strong>
            <span>{{ $student->full_name }}</span>
        </div>

        <div class="info-box">
            <strong>Student ID</strong>
            <span>{{ $student->student_id }}</span>
        </div>

        <div class="info-box">
            <strong>Section</strong>
            <span>{{ $student->section?->display_name ?? '—' }}</span>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Subject</th>
                <th class="text-center">Q1</th>
                <th class="text-center">Q2</th>
                <th class="text-center">Q3</th>
                <th class="text-center">Q4</th>
                <th class="text-center">Average</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($reportRows as $row)
                <tr>
                    <td>{{ $row['subject'] }}</td>
                    <td class="text-center">{{ $row['grades']['Q1'] ?? '—' }}</td>
                    <td class="text-center">{{ $row['grades']['Q2'] ?? '—' }}</td>
                    <td class="text-center">{{ $row['grades']['Q3'] ?? '—' }}</td>
                    <td class="text-center">{{ $row['grades']['Q4'] ?? '—' }}</td>
                    <td class="text-center">{{ $row['average'] ?? '—' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="text-center">No grades available for this student.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <div>
            <div>General Point Average</div>
            <div class="value">{{ $gpa !== null ? $gpa . '%' : '—' }}</div>
        </div>
        <div>
            <div>Status</div>
            <div class="value">{{ $gpa !== null ? ($gpa >= 75 ? 'Passed' : 'Failed') : 'Pending' }}</div>
        </div>
    </div>
</body>
</html>
